### ISSUE TITLE
Fatal error: Cannot read property %browser.id% of null

### ISSUE THREAD

**Issue by yavorskiy** [karma-runner/karma-junit-reporter#20]
Error happens if browser failed on start. Simplest case is when test case contained a Syntax Error. Here is [the example](https://github.com/yavorskiy/karma-junit-reporter-failure), run `grunt` to se the issue.

It is rather Karma problem, because `onBrowserComplete` is triggered twice and `suites` is `null`'ed by the second call. Here is some debugging output:

```
--> onRunStart
INFO [karma]: Karma v0.12.12 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 34.0.1847 (Mac OS X 10.9.2)]: Connected on socket zY0n_4LMncgG3V6ETzU9 with id 87250253
Chrome 34.0.1847 (Mac OS X 10.9.2) ERROR
  Uncaught SyntaxError: Unexpected end of input
  at /Users/siavorskyi/projects/CD/karma-junit-reporter-failure/test/syntax-error.spec.js:4

Chrome 34.0.1847 (Mac OS X 10.9.2): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
--> onBrowserStart 87250253
--> initliazeXmlForBrowser
Chrome 34.0.1847 (Mac OS X 10.9.2): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
--> onBrowserComplete 87250253 // suites is Object
--> onRunComplete
Chrome 34.0.1847 (Mac OS X 10.9.2): Executed 0 of 0 ERROR (0.004 secs / 0 secs)
--> onBrowserComplete 87250253 // suites is null
--> onRunComplete
```

**Comment by j0tunn** [comment]
Looks like it relates to karma itslef: https://github.com/karma-runner/karma/pull/1248
And it was fixed

**Comment by wookets** [comment]
Are we sure this was fixed? 

I'm seeing this in Karma 0.12.31.

Fatal error: Cannot read property '21770261' of null

**Comment by rhencke** [comment]
I believe I've distilled this error (or one very, very much like it) down to a minimal reproduction - this consistently errors with ```TypeError: Cannot read property 'somenumber' of null```

To reproduce:
```
git clone https://gist.github.com/rhencke/919d12c168e2300da133 bug20
cd bug20
npm install
npm test
```

**Comment by rhencke** [comment]
I think the underlying bug for this is actually https://github.com/karma-runner/karma/issues/1292

What is happening is that onRunComplete is called, and suites is set to null at https://github.com/karma-runner/karma-junit-reporter/blob/master/index.js#L120.  Then, later, a specSuccess/specSkipped/specFailure arrives (https://github.com/karma-runner/karma-junit-reporter/blob/v0.2.2/index.js#L89 from @hyzhak 's stack trace, but now https://github.com/karma-runner/karma-junit-reporter/blob/v0.3.8/index.js#L125 in the current release).  It attempts to reference suites, but suites has been set to null, and the TypeError occurs.

**Comment by tomwetjens** [comment]
Still experiencing this issue with karma 0.13.22 and karma-junit-reporter 0.4.0. Can you please merge the workaround by @alexeibs https://github.com/Megaputer/karma-junit-reporter/commit/d14b9bffe0d3d658b8a99e2854b3e8070e50c11f until https://github.com/karma-runner/karma/issues/1292 is solved?

**Comment by muhammad-ammar** [comment]
Still getting this issue wiht karma 0.13.22 and karma-junit-reporter 0.4.1. Any way to fix this issue?

**Comment by rhencke** [comment]
@muhammad-ammar We 'fixed' this locally in our case but it took code changes to karma-junit-reporter.  (I say 'fixed' because we did not address the underlying bug - we just made it work despite that).

I don't have the code changes handy but our workaround looked very much like the one in @alexeibs's fork here: https://github.com/Megaputer/karma-junit-reporter/commit/d14b9bffe0d3d658b8a99e2854b3e8070e50c11f and here: https://github.com/Megaputer/karma-junit-reporter/commit/9138c062c343262bccaa71571aca30d6e11d579b).  You may want to try that for now.

**Comment by muhammad-ammar** [comment]
:+1: @rhencke Thanks a lot for your reply and commit links.

**Comment by stramel** [comment]
https://github.com/karma-runner/karma/issues/1292

**Comment by wesleycho** [comment]
This error should be fixed in the karma-junit-reporter 1.2.0 release.
